### ISSUE TITLE
求助：无法获取clientkey

### ISSUE THREAD

**Issue by brokestar233** [nyaruhodoo/LiteLoader-NapCatCore-Template#1]
相关代码
`const clientKey = await NTcore.session.getTicketService().forceFetchClientKey('')['clientKey']`
版本信息
![f0cd1cd18bcc3f456ae0b7715da67bc7](https://github.com/user-attachments/assets/558fd270-87d2-482b-9186-7146bb2a7bb6)

希望正常获取clientkey但是实际返回的是undefined

**Comment by nyaruhodoo** [comment]
在开头已经说明，不要过于依赖 ntcore 提供的类型
如果一个函数的调用结果与你预期结果不同，那么大概率是参数给错或者不满足调用条件
你可以使用监听器看看qq自己是如何调用该函数的

其次，哥有钱赚能拉兄弟一把吗

**Comment by brokestar233** [comment]
> 在开头已经说明，不要过于依赖 ntcore 提供的类型 如果一个函数的调用结果与你预期结果不同，那么大概率是参数给错或者不满足调用条件 你可以使用监听器看看qq自己是如何调用该函数的
> 
> 其次，哥有钱赚能拉兄弟一把吗

第一次写插件不是很懂（其实对ts也是一知半解），去看了qq是这么调用的，但是我调用就一直卡着
调用使用的代码
```
const result = await invokeNative({
    cmdName: 'NodeIQQNTWrapperSession/create/getTicketService/forceFetchClientKey',
    args: ['']
  })
```
![8aa45ca96acf0f73c38362ddbd6b2b1d](https://github.com/user-attachments/assets/49a2f3f0-6e2a-4bb7-8bce-d1a2baa56a05)

**Comment by nyaruhodoo** [comment]
你犯了一个错误，首选你给出的log是hook wrapper
但你使用了hook ipc提供的invokeNative

第一个使用方式倒是没什么问题，但是你犯了一个语法错误，你可以自己再折腾折腾 ？
至少这个问题不是我的代码导致的...
